# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-14 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogArticle',
            new_name='BlogArticles',
        ),
        migrations.AlterModelOptions(
            name='blogarticles',
            options={'ordering': ('-publish',), 'verbose_name': '博客文章'},
        ),
    ]
